### ISSUE TITLE
gssapi/gssapi.h: No such file or directory

### ISSUE THREAD

**Issue by pjobson** [meritt/easymongo#8]
Installation with npm 2.14.4.

```
$ npm install easymongo -g
-
> kerberos@0.0.14 install /home/pjobson/node-v4.1.1/lib/node_modules/easymongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/pjobson/node-v4.1.1/lib/node_modules/easymongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/pjobson/node-v4.1.1/lib/node_modules/easymongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pjobson/node-v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/home/pjobson/node-v4.1.1/bin/node" "/home/pjobson/node-v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pjobson/node-v4.1.1/lib/node_modules/easymongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
easymongo@5.0.0 /home/pjobson/node-v4.1.1/lib/node_modules/easymongo
└── mongodb@2.0.43 (es6-promise@2.1.1, readable-stream@1.0.31, mongodb-core@1.2.12)
```

**Comment by pjobson** [comment]
Installed libkrb5-dev which fixed this.

**Comment by LaurensRietveld** [comment]
discussed in original mongodb bug tracker as well: https://jira.mongodb.org/browse/NODE-561
Disappointing, that mongodb now needs an external os dependency and is no longer self-contained

**Comment by rominf** [comment]
In openSUSE you have to install `krb5-devel`.

**Comment by gsaslis** [comment]
FWIW the package for CentOS is also `krb5-devel`

**Comment by ChinW** [comment]
> FWIW the package for CentOS is also `krb5-devel`

thanks man

**Comment by bryant1410** [comment]
For Ubuntu 18.04 I did:

```bash
sudo apt install krb5-multidev
```

**Comment by AaronJaegerVA** [comment]
> discussed in original mongodb bug tracker as well: https://jira.mongodb.org/browse/NODE-561
> Disappointing, that mongodb now needs an external os dependency and is no longer self-contained

Containers?

**Comment by FortunexFortune** [comment]
> FWIW the package for CentOS is also `krb5-devel`

thanks
